[package]
name = "xbraceml"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
log = "0.4.21"
simple_logger = "4.3.3"
